spring:
  application:
    name: spring-ai-demo
  ai:
    ollama:
      base-url: http://localhost:11434

logging:
  level:
    root: INFO
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
