spring:
  application:
    name: spring-ai-demo
  ai:
    vertex:
      ai:
        gemini:
          project-id: mms-amznscrape-dev-9e0e
          location: us-central1
          model: gemini-2.0-flash
        embedding:
          project-id: mms-amznscrape-dev-9e0e
          location: us-central1
          text:
            options:
              model: gemini-embedding-001
    mcp:
      client:
        enabled: false
        type: SYNC
        streamable-http:
          connections:
            my-weather-server:
              url: http://localhost:8081

  security:
    oauth2:
      client:
        provider:
          authserver:
            issuer-uri: http://localhost:9000
        registration:
          authserver:
            client-id: mcp-client
            client-secret: mcp-secret
            authorization-grant-type: authorization_code
            provider: authserver
          authserver-client-credentials:
            client-id: mcp-client
            client-secret: mcp-secret
            authorization-grant-type: client_credentials
            provider: authserver